# Generated by Django 4.2.1 on 2023-06-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invesments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='investment.investment'),
        ),
    ]
